### ISSUE TITLE
When emulating an iphone in chrome dev tools the input textbox becomes invisible

### ISSUE THREAD

**Issue by andyjdavis** [benfanderson/hangman#1]
Using Chrome on a mac to emulate an iphone and the text entry text box is invisible. I can click where I know it is an it then appears but you have to know its there already.

**Comment by benfanderson** [comment]
Added border styling to input textbox so now it is visible when emulating an iPhone in Chrome. Checked it using dev tools in Firefox and Safari and it also visible there.
